apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: order-processing
  name: order-processing
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5000
  selector:
    io.kompose.service: order-processing
