apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: "kompose convert -f docker-compose.yml"
    kompose.version: "1.32.0 (HEAD)"
  labels:
    app: order-processing
  name: order-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      annotations:
        kompose.cmd: "kompose convert -f docker-compose.yml"
        kompose.version: "1.32.0 (HEAD)"
      labels:
        app: order-processing
        network: ecomm-net
    spec:
      containers:
        - env:
            - name: PRODUCT_SERVICE_URL
              value: "http://product_management:5000"
          image: ananyavpes2ug21cs068/order_processing_service:latest
          name: order-processing-container
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
