apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\ashwi\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: product-management
  name: product-management
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5000
  selector:
    io.kompose.service: product-management
