apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\ashwi\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
    kompose.version: "1.32.0 (HEAD)"
  labels:
    app: user-auth
  name: user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\ashwi\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
        kompose.version: "1.32.0 (HEAD)"
      labels:
        app: user-auth
        network: ecomm-net
    spec:
      containers:
        - image: ashwinchandra/user_auth_service:latest
          name: user-auth-container
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
